version: "3"
services:
  ai-mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=aiapi
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  faker:
    image: dotronglong/faker:stable
    volumes:
      - /home/elouali/Desktop/projects/ai/ai-api/mocks:/home/elouali/Desktop/projects/ai/ai-api/mocks
    ports:
      - "3030:3030"